apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/grafana: "true"
        io.kompose.network/k6: "true"
        io.kompose.service: influxdb
    spec:
      containers:
        - env:
            - name: INFLUXDB_DB
              value: k6
          image: influxdb:1.8
          name: influxdb
          ports:
            - containerPort: 8086
          volumeMounts:
          - name: config-volume
            mountPath: /etc/influxdb
          - name: influxdb-volume
            mountPath: /var/lib/influxdb

      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          name: influxdb-config
      - name: influxdb-volume
        persistentVolumeClaim:
          claimName: influxdb
